// Generated by gencpp from file morse_service/MorseEncryptRequest.msg
// DO NOT EDIT!


#ifndef MORSE_SERVICE_MESSAGE_MORSEENCRYPTREQUEST_H
#define MORSE_SERVICE_MESSAGE_MORSEENCRYPTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace morse_service
{
template <class ContainerAllocator>
struct MorseEncryptRequest_
{
  typedef MorseEncryptRequest_<ContainerAllocator> Type;

  MorseEncryptRequest_()
    : mes()  {
    }
  MorseEncryptRequest_(const ContainerAllocator& _alloc)
    : mes(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mes_type;
  _mes_type mes;





  typedef boost::shared_ptr< ::morse_service::MorseEncryptRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morse_service::MorseEncryptRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MorseEncryptRequest_

typedef ::morse_service::MorseEncryptRequest_<std::allocator<void> > MorseEncryptRequest;

typedef boost::shared_ptr< ::morse_service::MorseEncryptRequest > MorseEncryptRequestPtr;
typedef boost::shared_ptr< ::morse_service::MorseEncryptRequest const> MorseEncryptRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morse_service::MorseEncryptRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morse_service::MorseEncryptRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace morse_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::morse_service::MorseEncryptRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morse_service::MorseEncryptRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morse_service::MorseEncryptRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morse_service::MorseEncryptRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morse_service::MorseEncryptRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morse_service::MorseEncryptRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morse_service::MorseEncryptRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e26588a7352b312645ab47dd17f0e4c2";
  }

  static const char* value(const ::morse_service::MorseEncryptRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe26588a7352b3126ULL;
  static const uint64_t static_value2 = 0x45ab47dd17f0e4c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::morse_service::MorseEncryptRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morse_service/MorseEncryptRequest";
  }

  static const char* value(const ::morse_service::MorseEncryptRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morse_service::MorseEncryptRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mes\n\
";
  }

  static const char* value(const ::morse_service::MorseEncryptRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morse_service::MorseEncryptRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MorseEncryptRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morse_service::MorseEncryptRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morse_service::MorseEncryptRequest_<ContainerAllocator>& v)
  {
    s << indent << "mes: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORSE_SERVICE_MESSAGE_MORSEENCRYPTREQUEST_H
