// Generated by gencpp from file morse_service/MorseTranslate.msg
// DO NOT EDIT!


#ifndef MORSE_SERVICE_MESSAGE_MORSETRANSLATE_H
#define MORSE_SERVICE_MESSAGE_MORSETRANSLATE_H

#include <ros/service_traits.h>


#include <morse_service/MorseTranslateRequest.h>
#include <morse_service/MorseTranslateResponse.h>


namespace morse_service
{

struct MorseTranslate
{

typedef MorseTranslateRequest Request;
typedef MorseTranslateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MorseTranslate
} // namespace morse_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::morse_service::MorseTranslate > {
  static const char* value()
  {
    return "c78a90a3ea05e29b7697d19c62ed1c62";
  }

  static const char* value(const ::morse_service::MorseTranslate&) { return value(); }
};

template<>
struct DataType< ::morse_service::MorseTranslate > {
  static const char* value()
  {
    return "morse_service/MorseTranslate";
  }

  static const char* value(const ::morse_service::MorseTranslate&) { return value(); }
};


// service_traits::MD5Sum< ::morse_service::MorseTranslateRequest> should match 
// service_traits::MD5Sum< ::morse_service::MorseTranslate > 
template<>
struct MD5Sum< ::morse_service::MorseTranslateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::morse_service::MorseTranslate >::value();
  }
  static const char* value(const ::morse_service::MorseTranslateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::morse_service::MorseTranslateRequest> should match 
// service_traits::DataType< ::morse_service::MorseTranslate > 
template<>
struct DataType< ::morse_service::MorseTranslateRequest>
{
  static const char* value()
  {
    return DataType< ::morse_service::MorseTranslate >::value();
  }
  static const char* value(const ::morse_service::MorseTranslateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::morse_service::MorseTranslateResponse> should match 
// service_traits::MD5Sum< ::morse_service::MorseTranslate > 
template<>
struct MD5Sum< ::morse_service::MorseTranslateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::morse_service::MorseTranslate >::value();
  }
  static const char* value(const ::morse_service::MorseTranslateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::morse_service::MorseTranslateResponse> should match 
// service_traits::DataType< ::morse_service::MorseTranslate > 
template<>
struct DataType< ::morse_service::MorseTranslateResponse>
{
  static const char* value()
  {
    return DataType< ::morse_service::MorseTranslate >::value();
  }
  static const char* value(const ::morse_service::MorseTranslateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MORSE_SERVICE_MESSAGE_MORSETRANSLATE_H
