// Generated by gencpp from file morse_service/MorseTranslateRequest.msg
// DO NOT EDIT!


#ifndef MORSE_SERVICE_MESSAGE_MORSETRANSLATEREQUEST_H
#define MORSE_SERVICE_MESSAGE_MORSETRANSLATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace morse_service
{
template <class ContainerAllocator>
struct MorseTranslateRequest_
{
  typedef MorseTranslateRequest_<ContainerAllocator> Type;

  MorseTranslateRequest_()
    : morse()  {
    }
  MorseTranslateRequest_(const ContainerAllocator& _alloc)
    : morse(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _morse_type;
  _morse_type morse;





  typedef boost::shared_ptr< ::morse_service::MorseTranslateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morse_service::MorseTranslateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MorseTranslateRequest_

typedef ::morse_service::MorseTranslateRequest_<std::allocator<void> > MorseTranslateRequest;

typedef boost::shared_ptr< ::morse_service::MorseTranslateRequest > MorseTranslateRequestPtr;
typedef boost::shared_ptr< ::morse_service::MorseTranslateRequest const> MorseTranslateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morse_service::MorseTranslateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morse_service::MorseTranslateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace morse_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::morse_service::MorseTranslateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morse_service::MorseTranslateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morse_service::MorseTranslateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morse_service::MorseTranslateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morse_service::MorseTranslateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morse_service::MorseTranslateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morse_service::MorseTranslateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4ffa6d7df23cd5db7167be916fc2c850";
  }

  static const char* value(const ::morse_service::MorseTranslateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4ffa6d7df23cd5dbULL;
  static const uint64_t static_value2 = 0x7167be916fc2c850ULL;
};

template<class ContainerAllocator>
struct DataType< ::morse_service::MorseTranslateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morse_service/MorseTranslateRequest";
  }

  static const char* value(const ::morse_service::MorseTranslateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morse_service::MorseTranslateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string morse\n\
";
  }

  static const char* value(const ::morse_service::MorseTranslateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morse_service::MorseTranslateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.morse);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MorseTranslateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morse_service::MorseTranslateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morse_service::MorseTranslateRequest_<ContainerAllocator>& v)
  {
    s << indent << "morse: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.morse);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORSE_SERVICE_MESSAGE_MORSETRANSLATEREQUEST_H
