(cl:defpackage morse_service-srv
  (:use )
  (:export
   "MORSEENCRYPT"
   "<MORSEENCRYPT-REQUEST>"
   "MORSEENCRYPT-REQUEST"
   "<MORSEENCRYPT-RESPONSE>"
   "MORSEENCRYPT-RESPONSE"
   "MORSETRANSLATE"
   "<MORSETRANSLATE-REQUEST>"
   "MORSETRANSLATE-REQUEST"
   "<MORSETRANSLATE-RESPONSE>"
   "MORSETRANSLATE-RESPONSE"
  ))

